- source/blog/2016-02-05-release-notes-6-33.md
- source/layouts/layout.erb
As per @taylorleese's feedback.
> Fix typos in the release notes

- source/blog/2016-07-08-release-notes-6-36.md
Release notes for 6.36. Ping @finagle/csl.
> Release notes 6.36

- source/blog/2017-03-14-release-notes-6-43.md
Announcing the March releases.
> March release notes, 6.43

- source/blog/2017-03-20-spring-planning.md
A blog post about 2017 spring planning.
> 2017 Spring Planning

- source/blog/2017-04-06-announce-removals.md
- source/layouts/layout.erb
A blog post regarding the upcoming removal of various modules.
> Upcoming module removal

- source/blog/2017-06-09-cla-requirement.md
> Fix the link in the CLA blog post

- source/blog/2017-06-09-cla-requirement.md
> Add a note about a better CLA process in the blog post

- source/blog/2017-10-12-fall-ing-for-finagle.md
> Fix type-o

- source/blog/2018-04-18-spring-review.md
The spring edition of our quarterly writeup
> Spring review 18

- source/blog/2018-06-15-release-notes.md
Please take a look at the 18.6.0 June Release Notes.
> 18.6.0 Release Notes

- source/blog/2018-07-11-release-notes.md
> July 2018 release post

- source/blog/2018-10-03-travis-ci.md
See text.
Here's an image of it rendered.
> TravisCI announcement for Finagle Org

- source/blog/2018-10-18-fall-review.md
- source/blog/2018-10-24-release-notes.md
Also, small formatting changes for Fall Review.
> 18.10.0 Release Notes

- source/blog/2018-11-13-release-notes.md
- source/blog/2018-12-18-release-notes.md
Also, small formatting change for 18.11.0 release notes
> 18.12.0 release notes

- source/blog/2019-04-19-release-notes.md
- source/layouts/layout.erb
Let me know what else to **Highlight**.
> Release notes 19.4

- source/blog/2019-08-07-release-notes.md
> August 2019 release notes

- source/blog/2019-10-09-release-notes.md
Problem
The release has no blog post of release notes
Solution
Release the release notes
> October release notes

- source/blog/2020-04-06-release-notes.md
Let's share some release notes.
> April 2020 release notes

- source/blog/2020-06-04-winter-spring.md
> Q1 review 2020

- source/blog/2020-07-22-release-notes.md
Create blog post entry for july release.
> July release notes

- source/blog/2020-07-22-release-notes.md
Remove accidental header from finatra changelog in blog post
> remove header from finatra changelog

- source/blog/2020-08-12-release-notes.md
Add new blog post for the 20.8.0 release.
> Add august release notes for 20.8.0

- source/blog/2020-08-27-release-notes.md
Release notes blog post for 20.8.1
> 20.8.1 release notes

- source/blog/2020-09-24-release-notes.md
- source/blog/2020-09-25-release-notes.md
Release notes blog post for 20.9.0
> 20.9.0 Release Notes

- source/blog/2020-12-11-release-notes.md
Release notes blog post for 20.12.0
> 2020.12.0 release notes

- source/blog/2021-01-19-release-notes.md
21.1.0 Release Notes blog post
> January Release Notes

- source/blog/2021-11-24-release-notes.md
Problem
We need a block post for the November release.
Solution
Add the blog post.
> November release blog post

- source/blog/2021-12-17-release-notes.md
Problem
We need a blog post for the December release.
Solution
Add the blog post.
> December release blog post

- source/blog/2022-06-01-announce-migrations.md
> Add announcement of sunseting kafka from Finatra core library
